name: msu_firebase_example
description: An example of using Firebase with Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  firebase_core: ^0.5.1
  firebase_messaging: ^8.0.0-dev.7
  cloud_firestore: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true